/* 
 * MBTA
 *
 * MBTA service API. https://www.mbta.com Source code: https://github.com/mbta/api
 *
 * OpenAPI spec version: 3.0
 * Contact: developer@mbta.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// BadRequestSource : A JSON-API error source

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct BadRequestSource {
  /// The name of parameter that caused the error
  #[serde(rename = "parameter")]
  parameter: Option<String>
}

impl BadRequestSource {
  /// A JSON-API error source
  pub fn new() -> BadRequestSource {
    BadRequestSource {
      parameter: None
    }
  }

  pub fn set_parameter(&mut self, parameter: String) {
    self.parameter = Some(parameter);
  }

  pub fn with_parameter(mut self, parameter: String) -> BadRequestSource {
    self.parameter = Some(parameter);
    self
  }

  pub fn parameter(&self) -> Option<&String> {
    self.parameter.as_ref()
  }

  pub fn reset_parameter(&mut self) {
    self.parameter = None;
  }

}



