/* 
 * MBTA
 *
 * MBTA service API. https://www.mbta.com Source code: https://github.com/mbta/api
 *
 * OpenAPI spec version: 3.0
 * Contact: developer@mbta.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// BadRequestErrors : A JSON-API error when a bad request is received

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct BadRequestErrors {
  /// The HTTP status code applicable to the problem
  #[serde(rename = "status")]
  status: Option<String>,
  #[serde(rename = "source")]
  source: Option<::models::BadRequestSource>,
  /// A short, human-readable summary of the problem
  #[serde(rename = "detail")]
  detail: Option<String>,
  /// An application-specific error code
  #[serde(rename = "code")]
  code: Option<String>
}

impl BadRequestErrors {
  /// A JSON-API error when a bad request is received
  pub fn new() -> BadRequestErrors {
    BadRequestErrors {
      status: None,
      source: None,
      detail: None,
      code: None
    }
  }

  pub fn set_status(&mut self, status: String) {
    self.status = Some(status);
  }

  pub fn with_status(mut self, status: String) -> BadRequestErrors {
    self.status = Some(status);
    self
  }

  pub fn status(&self) -> Option<&String> {
    self.status.as_ref()
  }

  pub fn reset_status(&mut self) {
    self.status = None;
  }

  pub fn set_source(&mut self, source: ::models::BadRequestSource) {
    self.source = Some(source);
  }

  pub fn with_source(mut self, source: ::models::BadRequestSource) -> BadRequestErrors {
    self.source = Some(source);
    self
  }

  pub fn source(&self) -> Option<&::models::BadRequestSource> {
    self.source.as_ref()
  }

  pub fn reset_source(&mut self) {
    self.source = None;
  }

  pub fn set_detail(&mut self, detail: String) {
    self.detail = Some(detail);
  }

  pub fn with_detail(mut self, detail: String) -> BadRequestErrors {
    self.detail = Some(detail);
    self
  }

  pub fn detail(&self) -> Option<&String> {
    self.detail.as_ref()
  }

  pub fn reset_detail(&mut self) {
    self.detail = None;
  }

  pub fn set_code(&mut self, code: String) {
    self.code = Some(code);
  }

  pub fn with_code(mut self, code: String) -> BadRequestErrors {
    self.code = Some(code);
    self
  }

  pub fn code(&self) -> Option<&String> {
    self.code.as_ref()
  }

  pub fn reset_code(&mut self) {
    self.code = None;
  }

}



