/* 
 * MBTA
 *
 * MBTA service API. https://www.mbta.com Source code: https://github.com/mbta/api
 *
 * OpenAPI spec version: 3.0
 * Contact: developer@mbta.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// BadRequest : A JSON-API error document when the server cannot or will not process the request due to something that is perceived to be a client error. 

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct BadRequest {
  #[serde(rename = "errors")]
  errors: Vec<::models::BadRequestErrors>
}

impl BadRequest {
  /// A JSON-API error document when the server cannot or will not process the request due to something that is perceived to be a client error. 
  pub fn new(errors: Vec<::models::BadRequestErrors>) -> BadRequest {
    BadRequest {
      errors: errors
    }
  }

  pub fn set_errors(&mut self, errors: Vec<::models::BadRequestErrors>) {
    self.errors = errors;
  }

  pub fn with_errors(mut self, errors: Vec<::models::BadRequestErrors>) -> BadRequest {
    self.errors = errors;
    self
  }

  pub fn errors(&self) -> &Vec<::models::BadRequestErrors> {
    &self.errors
  }


}



