/* 
 * MBTA
 *
 * MBTA service API. https://www.mbta.com Source code: https://github.com/mbta/api
 *
 * OpenAPI spec version: 3.0
 * Contact: developer@mbta.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct FacilityResourceRelationships {
  #[serde(rename = "stop")]
  stop: Option<::models::VehicleResourceRelationshipsStop>
}

impl FacilityResourceRelationships {
  pub fn new() -> FacilityResourceRelationships {
    FacilityResourceRelationships {
      stop: None
    }
  }

  pub fn set_stop(&mut self, stop: ::models::VehicleResourceRelationshipsStop) {
    self.stop = Some(stop);
  }

  pub fn with_stop(mut self, stop: ::models::VehicleResourceRelationshipsStop) -> FacilityResourceRelationships {
    self.stop = Some(stop);
    self
  }

  pub fn stop(&self) -> Option<&::models::VehicleResourceRelationshipsStop> {
    self.stop.as_ref()
  }

  pub fn reset_stop(&mut self) {
    self.stop = None;
  }

}



