/* 
 * MBTA
 *
 * MBTA service API. https://www.mbta.com Source code: https://github.com/mbta/api
 *
 * OpenAPI spec version: 3.0
 * Contact: developer@mbta.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// ForbiddenErrors : A JSON-API error when an invalid API key is received

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ForbiddenErrors {
  /// The HTTP status code applicable to the problem
  #[serde(rename = "status")]
  status: Option<String>,
  /// An application-specific error code
  #[serde(rename = "code")]
  code: Option<String>
}

impl ForbiddenErrors {
  /// A JSON-API error when an invalid API key is received
  pub fn new() -> ForbiddenErrors {
    ForbiddenErrors {
      status: None,
      code: None
    }
  }

  pub fn set_status(&mut self, status: String) {
    self.status = Some(status);
  }

  pub fn with_status(mut self, status: String) -> ForbiddenErrors {
    self.status = Some(status);
    self
  }

  pub fn status(&self) -> Option<&String> {
    self.status.as_ref()
  }

  pub fn reset_status(&mut self) {
    self.status = None;
  }

  pub fn set_code(&mut self, code: String) {
    self.code = Some(code);
  }

  pub fn with_code(mut self, code: String) -> ForbiddenErrors {
    self.code = Some(code);
    self
  }

  pub fn code(&self) -> Option<&String> {
    self.code.as_ref()
  }

  pub fn reset_code(&mut self) {
    self.code = None;
  }

}



