/* 
 * MBTA
 *
 * MBTA service API. https://www.mbta.com Source code: https://github.com/mbta/api
 *
 * OpenAPI spec version: 3.0
 * Contact: developer@mbta.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// Forbidden : A JSON-API error document when the API key is invalid

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct Forbidden {
  #[serde(rename = "errors")]
  errors: Vec<::models::ForbiddenErrors>
}

impl Forbidden {
  /// A JSON-API error document when the API key is invalid
  pub fn new(errors: Vec<::models::ForbiddenErrors>) -> Forbidden {
    Forbidden {
      errors: errors
    }
  }

  pub fn set_errors(&mut self, errors: Vec<::models::ForbiddenErrors>) {
    self.errors = errors;
  }

  pub fn with_errors(mut self, errors: Vec<::models::ForbiddenErrors>) -> Forbidden {
    self.errors = errors;
    self
  }

  pub fn errors(&self) -> &Vec<::models::ForbiddenErrors> {
    &self.errors
  }


}



