mod active_period;
pub use self::active_period::ActivePeriod;
mod activity;
pub use self::activity::Activity;
mod alert;
pub use self::alert::Alert;
mod alert_resource;
pub use self::alert_resource::AlertResource;
mod alert_resource_attributes;
pub use self::alert_resource_attributes::AlertResourceAttributes;
mod alert_resource_relationships;
pub use self::alert_resource_relationships::AlertResourceRelationships;
mod alert_resource_relationships_facility;
pub use self::alert_resource_relationships_facility::AlertResourceRelationshipsFacility;
mod alert_resource_relationships_facility_data;
pub use self::alert_resource_relationships_facility_data::AlertResourceRelationshipsFacilityData;
mod alert_resource_relationships_facility_links;
pub use self::alert_resource_relationships_facility_links::AlertResourceRelationshipsFacilityLinks;
mod alerts;
pub use self::alerts::Alerts;
mod bad_request;
pub use self::bad_request::BadRequest;
mod bad_request_errors;
pub use self::bad_request_errors::BadRequestErrors;
mod bad_request_source;
pub use self::bad_request_source::BadRequestSource;
mod facilities;
pub use self::facilities::Facilities;
mod facility;
pub use self::facility::Facility;
mod facility_property;
pub use self::facility_property::FacilityProperty;
mod facility_resource;
pub use self::facility_resource::FacilityResource;
mod facility_resource_attributes;
pub use self::facility_resource_attributes::FacilityResourceAttributes;
mod facility_resource_relationships;
pub use self::facility_resource_relationships::FacilityResourceRelationships;
mod forbidden;
pub use self::forbidden::Forbidden;
mod forbidden_errors;
pub use self::forbidden_errors::ForbiddenErrors;
mod informed_entity;
pub use self::informed_entity::InformedEntity;
mod line;
pub use self::line::Line;
mod line_resource;
pub use self::line_resource::LineResource;
mod line_resource_attributes;
pub use self::line_resource_attributes::LineResourceAttributes;
mod lines;
pub use self::lines::Lines;
mod live_facilities;
pub use self::live_facilities::LiveFacilities;
mod live_facility;
pub use self::live_facility::LiveFacility;
mod live_facility_resource;
pub use self::live_facility_resource::LiveFacilityResource;
mod live_facility_resource_attributes;
pub use self::live_facility_resource_attributes::LiveFacilityResourceAttributes;
mod not_found;
pub use self::not_found::NotFound;
mod not_found_errors;
pub use self::not_found_errors::NotFoundErrors;
mod not_found_source;
pub use self::not_found_source::NotFoundSource;
mod prediction_resource;
pub use self::prediction_resource::PredictionResource;
mod prediction_resource_attributes;
pub use self::prediction_resource_attributes::PredictionResourceAttributes;
mod prediction_resource_relationships;
pub use self::prediction_resource_relationships::PredictionResourceRelationships;
mod prediction_resource_relationships_alerts;
pub use self::prediction_resource_relationships_alerts::PredictionResourceRelationshipsAlerts;
mod prediction_resource_relationships_alerts_data;
pub use self::prediction_resource_relationships_alerts_data::PredictionResourceRelationshipsAlertsData;
mod prediction_resource_relationships_alerts_links;
pub use self::prediction_resource_relationships_alerts_links::PredictionResourceRelationshipsAlertsLinks;
mod prediction_resource_relationships_schedule;
pub use self::prediction_resource_relationships_schedule::PredictionResourceRelationshipsSchedule;
mod prediction_resource_relationships_schedule_data;
pub use self::prediction_resource_relationships_schedule_data::PredictionResourceRelationshipsScheduleData;
mod prediction_resource_relationships_schedule_links;
pub use self::prediction_resource_relationships_schedule_links::PredictionResourceRelationshipsScheduleLinks;
mod prediction_resource_relationships_vehicle;
pub use self::prediction_resource_relationships_vehicle::PredictionResourceRelationshipsVehicle;
mod prediction_resource_relationships_vehicle_data;
pub use self::prediction_resource_relationships_vehicle_data::PredictionResourceRelationshipsVehicleData;
mod prediction_resource_relationships_vehicle_links;
pub use self::prediction_resource_relationships_vehicle_links::PredictionResourceRelationshipsVehicleLinks;
mod predictions;
pub use self::predictions::Predictions;
mod route;
pub use self::route::Route;
mod route_pattern;
pub use self::route_pattern::RoutePattern;
mod route_pattern_resource;
pub use self::route_pattern_resource::RoutePatternResource;
mod route_pattern_resource_attributes;
pub use self::route_pattern_resource_attributes::RoutePatternResourceAttributes;
mod route_pattern_resource_relationships;
pub use self::route_pattern_resource_relationships::RoutePatternResourceRelationships;
mod route_pattern_resource_relationships_representative_trip;
pub use self::route_pattern_resource_relationships_representative_trip::RoutePatternResourceRelationshipsRepresentativeTrip;
mod route_pattern_resource_relationships_representative_trip_data;
pub use self::route_pattern_resource_relationships_representative_trip_data::RoutePatternResourceRelationshipsRepresentativeTripData;
mod route_pattern_resource_relationships_representative_trip_links;
pub use self::route_pattern_resource_relationships_representative_trip_links::RoutePatternResourceRelationshipsRepresentativeTripLinks;
mod route_patterns;
pub use self::route_patterns::RoutePatterns;
mod route_resource;
pub use self::route_resource::RouteResource;
mod route_resource_attributes;
pub use self::route_resource_attributes::RouteResourceAttributes;
mod routes;
pub use self::routes::Routes;
mod schedule_resource;
pub use self::schedule_resource::ScheduleResource;
mod schedule_resource_attributes;
pub use self::schedule_resource_attributes::ScheduleResourceAttributes;
mod schedule_resource_relationships;
pub use self::schedule_resource_relationships::ScheduleResourceRelationships;
mod schedule_resource_relationships_prediction;
pub use self::schedule_resource_relationships_prediction::ScheduleResourceRelationshipsPrediction;
mod schedule_resource_relationships_prediction_data;
pub use self::schedule_resource_relationships_prediction_data::ScheduleResourceRelationshipsPredictionData;
mod schedule_resource_relationships_prediction_links;
pub use self::schedule_resource_relationships_prediction_links::ScheduleResourceRelationshipsPredictionLinks;
mod schedules;
pub use self::schedules::Schedules;
mod service;
pub use self::service::Service;
mod service_resource;
pub use self::service_resource::ServiceResource;
mod service_resource_attributes;
pub use self::service_resource_attributes::ServiceResourceAttributes;
mod services;
pub use self::services::Services;
mod shape;
pub use self::shape::Shape;
mod shape_resource;
pub use self::shape_resource::ShapeResource;
mod shape_resource_attributes;
pub use self::shape_resource_attributes::ShapeResourceAttributes;
mod shape_resource_relationships;
pub use self::shape_resource_relationships::ShapeResourceRelationships;
mod shape_resource_relationships_route;
pub use self::shape_resource_relationships_route::ShapeResourceRelationshipsRoute;
mod shape_resource_relationships_route_data;
pub use self::shape_resource_relationships_route_data::ShapeResourceRelationshipsRouteData;
mod shape_resource_relationships_route_links;
pub use self::shape_resource_relationships_route_links::ShapeResourceRelationshipsRouteLinks;
mod shape_resource_relationships_stops;
pub use self::shape_resource_relationships_stops::ShapeResourceRelationshipsStops;
mod shape_resource_relationships_stops_data;
pub use self::shape_resource_relationships_stops_data::ShapeResourceRelationshipsStopsData;
mod shape_resource_relationships_stops_links;
pub use self::shape_resource_relationships_stops_links::ShapeResourceRelationshipsStopsLinks;
mod shapes;
pub use self::shapes::Shapes;
mod stop;
pub use self::stop::Stop;
mod stop_resource;
pub use self::stop_resource::StopResource;
mod stop_resource_attributes;
pub use self::stop_resource_attributes::StopResourceAttributes;
mod stop_resource_relationships;
pub use self::stop_resource_relationships::StopResourceRelationships;
mod stop_resource_relationships_parent_station;
pub use self::stop_resource_relationships_parent_station::StopResourceRelationshipsParentStation;
mod stop_resource_relationships_parent_station_data;
pub use self::stop_resource_relationships_parent_station_data::StopResourceRelationshipsParentStationData;
mod stop_resource_relationships_parent_station_links;
pub use self::stop_resource_relationships_parent_station_links::StopResourceRelationshipsParentStationLinks;
mod stops;
pub use self::stops::Stops;
mod too_many_requests;
pub use self::too_many_requests::TooManyRequests;
mod too_many_requests_errors;
pub use self::too_many_requests_errors::TooManyRequestsErrors;
mod trip;
pub use self::trip::Trip;
mod trip_resource;
pub use self::trip_resource::TripResource;
mod trip_resource_attributes;
pub use self::trip_resource_attributes::TripResourceAttributes;
mod trip_resource_relationships;
pub use self::trip_resource_relationships::TripResourceRelationships;
mod trip_resource_relationships_route_pattern;
pub use self::trip_resource_relationships_route_pattern::TripResourceRelationshipsRoutePattern;
mod trip_resource_relationships_route_pattern_data;
pub use self::trip_resource_relationships_route_pattern_data::TripResourceRelationshipsRoutePatternData;
mod trip_resource_relationships_route_pattern_links;
pub use self::trip_resource_relationships_route_pattern_links::TripResourceRelationshipsRoutePatternLinks;
mod trip_resource_relationships_service;
pub use self::trip_resource_relationships_service::TripResourceRelationshipsService;
mod trip_resource_relationships_service_data;
pub use self::trip_resource_relationships_service_data::TripResourceRelationshipsServiceData;
mod trip_resource_relationships_service_links;
pub use self::trip_resource_relationships_service_links::TripResourceRelationshipsServiceLinks;
mod trip_resource_relationships_shape;
pub use self::trip_resource_relationships_shape::TripResourceRelationshipsShape;
mod trip_resource_relationships_shape_data;
pub use self::trip_resource_relationships_shape_data::TripResourceRelationshipsShapeData;
mod trip_resource_relationships_shape_links;
pub use self::trip_resource_relationships_shape_links::TripResourceRelationshipsShapeLinks;
mod trips;
pub use self::trips::Trips;
mod vehicle;
pub use self::vehicle::Vehicle;
mod vehicle_included;
pub use self::vehicle_included::VehicleIncluded;
mod vehicle_links;
pub use self::vehicle_links::VehicleLinks;
mod vehicle_resource;
pub use self::vehicle_resource::VehicleResource;
mod vehicle_resource_attributes;
pub use self::vehicle_resource_attributes::VehicleResourceAttributes;
mod vehicle_resource_relationships;
pub use self::vehicle_resource_relationships::VehicleResourceRelationships;
mod vehicle_resource_relationships_stop;
pub use self::vehicle_resource_relationships_stop::VehicleResourceRelationshipsStop;
mod vehicle_resource_relationships_stop_data;
pub use self::vehicle_resource_relationships_stop_data::VehicleResourceRelationshipsStopData;
mod vehicle_resource_relationships_stop_links;
pub use self::vehicle_resource_relationships_stop_links::VehicleResourceRelationshipsStopLinks;
mod vehicle_resource_relationships_trip;
pub use self::vehicle_resource_relationships_trip::VehicleResourceRelationshipsTrip;
mod vehicle_resource_relationships_trip_data;
pub use self::vehicle_resource_relationships_trip_data::VehicleResourceRelationshipsTripData;
mod vehicle_resource_relationships_trip_links;
pub use self::vehicle_resource_relationships_trip_links::VehicleResourceRelationshipsTripLinks;
mod vehicles;
pub use self::vehicles::Vehicles;
mod vehicles_links;
pub use self::vehicles_links::VehiclesLinks;

// TODO(farcaller): sort out files
pub struct File;
