/* 
 * MBTA
 *
 * MBTA service API. https://www.mbta.com Source code: https://github.com/mbta/api
 *
 * OpenAPI spec version: 3.0
 * Contact: developer@mbta.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// NotFound : A JSON-API error document when a resource is not found

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct NotFound {
  #[serde(rename = "errors")]
  errors: Vec<::models::NotFoundErrors>
}

impl NotFound {
  /// A JSON-API error document when a resource is not found
  pub fn new(errors: Vec<::models::NotFoundErrors>) -> NotFound {
    NotFound {
      errors: errors
    }
  }

  pub fn set_errors(&mut self, errors: Vec<::models::NotFoundErrors>) {
    self.errors = errors;
  }

  pub fn with_errors(mut self, errors: Vec<::models::NotFoundErrors>) -> NotFound {
    self.errors = errors;
    self
  }

  pub fn errors(&self) -> &Vec<::models::NotFoundErrors> {
    &self.errors
  }


}



