/* 
 * MBTA
 *
 * MBTA service API. https://www.mbta.com Source code: https://github.com/mbta/api
 *
 * OpenAPI spec version: 3.0
 * Contact: developer@mbta.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct StopResourceRelationships {
  #[serde(rename = "parent_station")]
  parent_station: Option<::models::StopResourceRelationshipsParentStation>
}

impl StopResourceRelationships {
  pub fn new() -> StopResourceRelationships {
    StopResourceRelationships {
      parent_station: None
    }
  }

  pub fn set_parent_station(&mut self, parent_station: ::models::StopResourceRelationshipsParentStation) {
    self.parent_station = Some(parent_station);
  }

  pub fn with_parent_station(mut self, parent_station: ::models::StopResourceRelationshipsParentStation) -> StopResourceRelationships {
    self.parent_station = Some(parent_station);
    self
  }

  pub fn parent_station(&self) -> Option<&::models::StopResourceRelationshipsParentStation> {
    self.parent_station.as_ref()
  }

  pub fn reset_parent_station(&mut self) {
    self.parent_station = None;
  }

}



