/* 
 * MBTA
 *
 * MBTA service API. https://www.mbta.com Source code: https://github.com/mbta/api
 *
 * OpenAPI spec version: 3.0
 * Contact: developer@mbta.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// Stop : A JSON-API document with a single [StopResource](#stopresource) resource

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct Stop {
  #[serde(rename = "links")]
  links: Option<::models::VehicleLinks>,
  /// Included resources
  #[serde(rename = "included")]
  included: Option<Vec<::models::VehicleIncluded>>,
  #[serde(rename = "data")]
  data: ::models::StopResource
}

impl Stop {
  /// A JSON-API document with a single [StopResource](#stopresource) resource
  pub fn new(data: ::models::StopResource) -> Stop {
    Stop {
      links: None,
      included: None,
      data: data
    }
  }

  pub fn set_links(&mut self, links: ::models::VehicleLinks) {
    self.links = Some(links);
  }

  pub fn with_links(mut self, links: ::models::VehicleLinks) -> Stop {
    self.links = Some(links);
    self
  }

  pub fn links(&self) -> Option<&::models::VehicleLinks> {
    self.links.as_ref()
  }

  pub fn reset_links(&mut self) {
    self.links = None;
  }

  pub fn set_included(&mut self, included: Vec<::models::VehicleIncluded>) {
    self.included = Some(included);
  }

  pub fn with_included(mut self, included: Vec<::models::VehicleIncluded>) -> Stop {
    self.included = Some(included);
    self
  }

  pub fn included(&self) -> Option<&Vec<::models::VehicleIncluded>> {
    self.included.as_ref()
  }

  pub fn reset_included(&mut self) {
    self.included = None;
  }

  pub fn set_data(&mut self, data: ::models::StopResource) {
    self.data = data;
  }

  pub fn with_data(mut self, data: ::models::StopResource) -> Stop {
    self.data = data;
    self
  }

  pub fn data(&self) -> &::models::StopResource {
    &self.data
  }


}



