/* 
 * MBTA
 *
 * MBTA service API. https://www.mbta.com Source code: https://github.com/mbta/api
 *
 * OpenAPI spec version: 3.0
 * Contact: developer@mbta.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// TooManyRequests : A JSON-API error document when rate limited

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct TooManyRequests {
  #[serde(rename = "errors")]
  errors: Vec<::models::TooManyRequestsErrors>
}

impl TooManyRequests {
  /// A JSON-API error document when rate limited
  pub fn new(errors: Vec<::models::TooManyRequestsErrors>) -> TooManyRequests {
    TooManyRequests {
      errors: errors
    }
  }

  pub fn set_errors(&mut self, errors: Vec<::models::TooManyRequestsErrors>) {
    self.errors = errors;
  }

  pub fn with_errors(mut self, errors: Vec<::models::TooManyRequestsErrors>) -> TooManyRequests {
    self.errors = errors;
    self
  }

  pub fn errors(&self) -> &Vec<::models::TooManyRequestsErrors> {
    &self.errors
  }


}



