/* 
 * MBTA
 *
 * MBTA service API. https://www.mbta.com Source code: https://github.com/mbta/api
 *
 * OpenAPI spec version: 3.0
 * Contact: developer@mbta.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct TripResourceRelationshipsRoutePattern {
  #[serde(rename = "links")]
  links: Option<::models::TripResourceRelationshipsRoutePatternLinks>,
  #[serde(rename = "data")]
  data: Option<::models::TripResourceRelationshipsRoutePatternData>
}

impl TripResourceRelationshipsRoutePattern {
  pub fn new() -> TripResourceRelationshipsRoutePattern {
    TripResourceRelationshipsRoutePattern {
      links: None,
      data: None
    }
  }

  pub fn set_links(&mut self, links: ::models::TripResourceRelationshipsRoutePatternLinks) {
    self.links = Some(links);
  }

  pub fn with_links(mut self, links: ::models::TripResourceRelationshipsRoutePatternLinks) -> TripResourceRelationshipsRoutePattern {
    self.links = Some(links);
    self
  }

  pub fn links(&self) -> Option<&::models::TripResourceRelationshipsRoutePatternLinks> {
    self.links.as_ref()
  }

  pub fn reset_links(&mut self) {
    self.links = None;
  }

  pub fn set_data(&mut self, data: ::models::TripResourceRelationshipsRoutePatternData) {
    self.data = Some(data);
  }

  pub fn with_data(mut self, data: ::models::TripResourceRelationshipsRoutePatternData) -> TripResourceRelationshipsRoutePattern {
    self.data = Some(data);
    self
  }

  pub fn data(&self) -> Option<&::models::TripResourceRelationshipsRoutePatternData> {
    self.data.as_ref()
  }

  pub fn reset_data(&mut self) {
    self.data = None;
  }

}



